// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: data_reset.sql

package database

import (
	"context"
)

const resetData = `-- name: ResetData :exec
DELETE FROM users
`

func (q *Queries) ResetData(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetData)
	return err
}
