// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_chirp.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getChirp = `-- name: GetChirp :one
SELECT id FROM chirps WHERE id = $1
`

func (q *Queries) GetChirp(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getChirp, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}
