// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: update_user_info.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateUserInfo = `-- name: UpdateUserInfo :one
UPDATE users
SET email = $1, password = $2
WHERE id = $3
RETURNING id, created_at, updated_at, email
`

type UpdateUserInfoParams struct {
	Email    string
	Password string
	ID       uuid.UUID
}

type UpdateUserInfoRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
}

func (q *Queries) UpdateUserInfo(ctx context.Context, arg UpdateUserInfoParams) (UpdateUserInfoRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserInfo, arg.Email, arg.Password, arg.ID)
	var i UpdateUserInfoRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}
